kind: pipeline
name: default

steps:
- name: php-fpm
  image: plugins/docker
  settings:
    repo: chrishsieh/php-fpm
    dockerfile: ./Dockerfile
    context: .
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - latest